name: Front build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull & build front
      uses: appleboy/ssh-action@master 
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SECRET_KEY }}
        port: 22
        script: |
          cd /home/morty/front
          rm -rf ./build
          git fetch --all
          git checkout main
          git reset --hard HEAD
          git pull
          cp -f /home/morty/env/.env.front /home/morty/front/.env
          yarn install
          yarn build
